import type { DiscoverCard } from "@/types/discover";

export const BUSAN_CARDS: Omit<DiscoverCard, "id">[] = [
  {
    name: "海雲台海水浴場",
    category: "spot",
    description: "東海經典海灘、夏日戲水",
    popularity: 96,
    latitude: 35.1587,
    longitude: 129.1604,
    tags: ["海景", "必訪"],
    area: "海雲台",
  },
  {
    name: "甘川文化村",
    category: "spot",
    description: "彩色階梯村落、小王子打卡點",
    popularity: 94,
    latitude: 35.0975,
    longitude: 129.0107,
    tags: ["網美", "文化"],
    area: "西面",
  },
  {
    name: "札嘎其市場",
    category: "food",
    description: "活海鮮、現做刺身、釜山魚市",
    popularity: 93,
    latitude: 35.0968,
    longitude: 129.0307,
    tags: ["海鮮", "必吃"],
    area: "南浦",
  },
  {
    name: "廣安里大橋夜景",
    category: "spot",
    description: "每月燈光秀，海灘散步",
    popularity: 91,
    latitude: 35.1532,
    longitude: 129.1186,
    tags: ["夜景", "海景"],
    area: "廣安里",
  },
  {
    name: "烤五花肉（釜山式）",
    category: "food",
    description: "厚切豬五花、包生菜蒜片",
    popularity: 90,
    latitude: 35.1796,
    longitude: 129.0756,
    tags: ["必吃", "烤肉"],
    area: "西面",
  },
  {
    name: "太宗台",
    category: "spot",
    description: "懸崖海景、燈塔、遊艇",
    popularity: 88,
    latitude: 35.0515,
    longitude: 129.0855,
    tags: ["海景", "郊遊"],
    area: "影島",
  },
  {
    name: "松島海上步道",
    category: "spot",
    description: "透明玻璃橋，海浪腳下穿行",
    popularity: 87,
    latitude: 35.078,
    longitude: 129.023,
    tags: ["網美", "海景"],
    area: "松島",
  },
  {
    name: "機張蚌肉 & 海鮮鍋",
    category: "food",
    description: "機張海岸新鮮蚌、刀削麵",
    popularity: 86,
    latitude: 35.362,
    longitude: 129.224,
    tags: ["海鮮", "一日遊"],
    area: "機張",
  },
  {
    name: "西面購物街",
    category: "spot",
    description: "釜山最熱鬧商圈、地下街",
    popularity: 85,
    latitude: 35.1578,
    longitude: 129.0595,
    tags: ["購物"],
    area: "西面",
  },
  {
    name: "釜山魚糕（BIFF 廣場一帶）",
    category: "food",
    description: "熱湯魚糕串，電影節故鄉小吃",
    popularity: 84,
    latitude: 35.0977,
    longitude: 129.0265,
    tags: ["小吃", "伴手禮"],
    area: "南浦",
  },
  {
    name: "五六島天空步道",
    category: "spot",
    description: "離島岩岸、透明觀景平台",
    popularity: 83,
    latitude: 35.0948,
    longitude: 129.1188,
    tags: ["海景", "健行"],
    area: "東區",
  },
  {
    name: "冬柏島 APEC 公園",
    category: "spot",
    description: "海雲台旁海岸步道、遠眺廣安里",
    popularity: 82,
    latitude: 35.1582,
    longitude: 129.173,
    tags: ["散步", "海景"],
    area: "海雲台",
  },
  {
    name: "豬肉湯飯",
    category: "food",
    description: "釜山早餐代表，解酒暖胃",
    popularity: 81,
    latitude: 35.179,
    longitude: 129.074,
    tags: ["早餐", "在地"],
    area: "西面",
  },
  {
    name: "釜山塔（龍頭山公園）",
    category: "spot",
    description: "港口全景、纜車上龍頭山",
    popularity: 80,
    latitude: 35.0992,
    longitude: 129.0324,
    tags: ["夜景", "地標"],
    area: "南浦",
  },
  {
    name: "白淺灘文化村",
    category: "spot",
    description: "階梯壁畫、海景咖啡，甘川之外的小眾",
    popularity: 79,
    latitude: 35.0785,
    longitude: 129.045,
    tags: ["網美", "海景"],
    area: "影島",
  },
  {
    name: "Spa Land 汗蒸幕（Centum City）",
    category: "spot",
    description: "世界最大百貨旁的韓式三溫暖",
    popularity: 77,
    latitude: 35.1685,
    longitude: 129.1312,
    tags: ["放鬆", "體驗"],
    area: "海雲台",
  },
  {
    name: "釜山國際電影街（BIFF 廣場）",
    category: "spot",
    description: "明星手印、街頭小吃、港口風光",
    popularity: 76,
    latitude: 35.0979,
    longitude: 129.0268,
    tags: ["文化", "夜景"],
    area: "南浦",
  },
  {
    name: "鎮海樓 & 釜山港",
    category: "spot",
    description: "海雲台往機張途中的海岸公路",
    popularity: 68,
    latitude: 35.244,
    longitude: 129.222,
    tags: ["海景", "開車"],
    area: "機張",
  },
];
