import type { DiscoverCard } from "@/types/discover";

export const OSAKA_CARDS: Omit<DiscoverCard, "id">[] = [
  {
    name: "道頓堀（固力果看板）",
    category: "spot",
    description: "霓虹招牌、章魚燒、串炸一條街",
    popularity: 97,
    latitude: 34.6687,
    longitude: 135.5013,
    tags: ["必訪", "夜景"],
    area: "難波",
  },
  {
    name: "大阪城",
    category: "spot",
    description: "豐臣秀吉城堡、天守閣與護城河",
    popularity: 94,
    latitude: 34.6873,
    longitude: 135.5262,
    tags: ["歷史", "必訪"],
    area: "中央區",
  },
  {
    name: "章魚燒（たこ焼）",
    category: "food",
    description: "大阪靈魂小吃，道頓堀名店林立",
    popularity: 93,
    latitude: 34.6695,
    longitude: 135.502,
    tags: ["必吃", "小吃"],
    area: "難波",
  },
  {
    name: "新世界 & 通天閣",
    category: "spot",
    description: "復古商圈、串炸起源地",
    popularity: 91,
    latitude: 34.6525,
    longitude: 135.5063,
    tags: ["復古", "地標"],
    area: "新世界",
  },
  {
    name: "串炸（新世界／法善寺橫丁）",
    category: "food",
    description: "一次只沾醬一次的大阪規矩",
    popularity: 90,
    latitude: 34.653,
    longitude: 135.505,
    tags: ["必吃", "居酒屋"],
    area: "新世界",
  },
  {
    name: "黑門市場",
    category: "food",
    description: "大阪的廚房，海鮮丼、和牛",
    popularity: 89,
    latitude: 34.6653,
    longitude: 135.5063,
    tags: ["市場", "海鮮"],
    area: "難波",
  },
  {
    name: "心齋橋筋商店街",
    category: "spot",
    description: "拱廊購物、藥妝、潮流",
    popularity: 88,
    latitude: 34.672,
    longitude: 135.501,
    tags: ["購物"],
    area: "心齋橋",
  },
  {
    name: "梅田藍天大廈空中庭園",
    category: "spot",
    description: "環狀夜景展望台，夕陽人氣",
    popularity: 87,
    latitude: 34.7054,
    longitude: 135.4904,
    tags: ["夜景", "地標"],
    area: "梅田",
  },
  {
    name: "大阪日本環球影城",
    category: "spot",
    description: "瑪利歐、哈利波特等主題設施",
    popularity: 86,
    latitude: 34.6654,
    longitude: 135.4323,
    tags: ["主題樂園", "一日遊"],
    area: "此花區",
  },
  {
    name: "法善寺橫丁",
    category: "spot",
    description: "石板小巷、串炸與關西居酒屋",
    popularity: 85,
    latitude: 34.6678,
    longitude: 135.5035,
    tags: ["夜生活", "散步"],
    area: "難波",
  },
  {
    name: "河豚料理（道頓堀）",
    category: "food",
    description: "虎河豚刺身、火鍋高級體驗",
    popularity: 84,
    latitude: 34.669,
    longitude: 135.5005,
    tags: ["高級", "必吃"],
    area: "難波",
  },
  {
    name: "四天王寺",
    category: "spot",
    description: "日本最古老官寺之一",
    popularity: 78,
    latitude: 34.6544,
    longitude: 135.5165,
    tags: ["寺廟", "歷史"],
    area: "天王寺",
  },
  {
    name: "美國村（アメ村）",
    category: "spot",
    description: "古著、潮流、美式文化",
    popularity: 82,
    latitude: 34.6725,
    longitude: 135.498,
    tags: ["年輕", "購物"],
    area: "心齋橋",
  },
  {
    name: "大阪燒（お好み焼き）",
    category: "food",
    description: "千房、美津の等名店雲集",
    popularity: 88,
    latitude: 34.668,
    longitude: 135.504,
    tags: ["必吃", "鐵板"],
    area: "難波",
  },
  {
    name: "住吉大社",
    category: "spot",
    description: "朱紅鳥居、反橋倒影經典照",
    popularity: 80,
    latitude: 34.6544,
    longitude: 135.4933,
    tags: ["神社", "網美"],
    area: "住吉",
  },
  {
    name: "神戶牛（大阪店）",
    category: "food",
    description: "鄰近神戶的和牛燒肉、壽喜燒",
    popularity: 79,
    latitude: 34.693,
    longitude: 135.502,
    tags: ["和牛"],
    area: "北區",
  },
  {
    name: "天滿宮 & 天神橋筋",
    category: "spot",
    description: "學問之神、日本最長商店街",
    popularity: 77,
    latitude: 34.7045,
    longitude: 135.5125,
    tags: ["商店街", "文化"],
    area: "北區",
  },
  {
    name: "勝尾寺（達摩）",
    category: "spot",
    description: "達摩奉納寺，一日遊郊區",
    popularity: 74,
    latitude: 34.567,
    longitude: 135.567,
    tags: ["郊遊", "神社"],
    area: "箕面",
  },
];
