import type { DiscoverCard } from "@/types/discover";

export const SEOUL_CARDS: Omit<DiscoverCard, "id">[] = [
  {
    name: "景福宮",
    category: "spot",
    description: "朝鮮王朝正宮，韓服體驗與守門儀式",
    popularity: 96,
    latitude: 37.5796,
    longitude: 126.977,
    tags: ["宮殿", "必訪"],
    area: "鍾路",
  },
  {
    name: "北村韓屋村",
    category: "spot",
    description: "傳統韓屋巷弄，咖啡廳與工藝體驗",
    popularity: 93,
    latitude: 37.5826,
    longitude: 126.9831,
    tags: ["韓屋", "網美"],
    area: "鍾路",
  },
  {
    name: "明洞購物街",
    category: "spot",
    description: "美妝、潮流、小吃集中地",
    popularity: 95,
    latitude: 37.5636,
    longitude: 126.985,
    tags: ["購物", "必訪"],
    area: "明洞",
  },
  {
    name: "弘大商圈",
    category: "spot",
    description: "街頭表演、夜店、年輕潮流",
    popularity: 92,
    latitude: 37.5563,
    longitude: 126.9236,
    tags: ["夜生活", "年輕"],
    area: "弘大",
  },
  {
    name: "廣藏市場（綠豆煎餅）",
    category: "food",
    description: "傳統市場，綠豆煎、生拌牛肉",
    popularity: 91,
    latitude: 37.57,
    longitude: 126.9996,
    tags: ["市場", "必吃"],
    area: "鍾路",
  },
  {
    name: "N 首爾塔（南山塔）",
    category: "spot",
    description: "愛情鎖、首爾全景夜景",
    popularity: 90,
    latitude: 37.5512,
    longitude: 126.9882,
    tags: ["夜景", "地標"],
    area: "南山",
  },
  {
    name: "韓式炸雞配啤酒",
    category: "food",
    description: "치맥文化，外帶炸雞名店林立",
    popularity: 89,
    latitude: 37.5665,
    longitude: 126.978,
    tags: ["必吃", "夜生活"],
    area: "弘大",
  },
  {
    name: "參雞湯（土俗村／清潭洞）",
    category: "food",
    description: "夏日補身名物，糯米塞雞",
    popularity: 88,
    latitude: 37.5265,
    longitude: 127.0275,
    tags: ["必吃", "傳統"],
    area: "江南",
  },
  {
    name: "梨泰院",
    category: "spot",
    description: "異國餐廳、酒吧、萬聖節街頭",
    popularity: 87,
    latitude: 37.5344,
    longitude: 126.9943,
    tags: ["夜生活", "異國"],
    area: "龍山",
  },
  {
    name: "漢江公園野餐",
    category: "spot",
    description: "外帶炸雞、租野餐墊，在地週末儀式",
    popularity: 86,
    latitude: 37.5285,
    longitude: 126.9326,
    tags: ["野餐", "放鬆"],
    area: "汝矣島",
  },
  {
    name: "東大門設計廣場 DDP",
    category: "spot",
    description: "扎哈建築、夜間燈光、批發購物",
    popularity: 85,
    latitude: 37.5665,
    longitude: 127.009,
    tags: ["建築", "購物"],
    area: "東大門",
  },
  {
    name: "聖水洞（咖啡 & 選物）",
    category: "spot",
    description: "文青咖啡、快時尚、快閃店",
    popularity: 84,
    latitude: 37.5445,
    longitude: 127.0555,
    tags: ["文青", "網美"],
    area: "聖水",
  },
  {
    name: "南山市場",
    category: "food",
    description: "血腸、辣炒年糕、山頂夜景",
    popularity: 83,
    latitude: 37.5584,
    longitude: 126.9876,
    tags: ["市場", "夜景"],
    area: "南山",
  },
  {
    name: "部隊鍋",
    category: "food",
    description: "泡麵、火腿、起司融為一鍋的戰後美食",
    popularity: 82,
    latitude: 37.563,
    longitude: 126.984,
    tags: ["鍋物", "在地"],
    area: "明洞",
  },
  {
    name: "仁寺洞 & 三清洞",
    category: "spot",
    description: "傳統茶屋、工藝、文創小店",
    popularity: 81,
    latitude: 37.5735,
    longitude: 126.9835,
    tags: ["文化", "散步"],
    area: "鍾路",
  },
  {
    name: "通仁市場 早餐",
    category: "food",
    description: "用代幣換便當盒的觀光早餐體驗",
    popularity: 78,
    latitude: 37.579,
    longitude: 126.9695,
    tags: ["早餐", "市場"],
    area: "西村",
  },
  {
    name: "國立中央博物館",
    category: "spot",
    description: "韓國歷史文物，雨天室內首選",
    popularity: 72,
    latitude: 37.524,
    longitude: 126.9804,
    tags: ["博物館"],
    area: "龍山",
  },
  {
    name: "狎鷗亭 & 江南",
    category: "spot",
    description: "精品、醫美、K-pop 周邊",
    popularity: 80,
    latitude: 37.527,
    longitude: 127.028,
    tags: ["購物", "時尚"],
    area: "江南",
  },
];
