import type { DiscoverCard } from "@/types/discover";

export const TAIPEI_CARDS: Omit<DiscoverCard, "id">[] = [
  {
    name: "台北 101 觀景台",
    category: "spot",
    description: "地標夜景、跨年煙火首選",
    popularity: 97,
    latitude: 25.0339,
    longitude: 121.5645,
    tags: ["地標", "夜景"],
    area: "信義",
  },
  {
    name: "永康街（牛肉麵、芒果冰）",
    category: "food",
    description: "觀光美食街，青椒牛肉麵、冰品名店聚集",
    popularity: 94,
    latitude: 25.0325,
    longitude: 121.5296,
    tags: ["必吃", "散步"],
    area: "大安",
  },
  {
    name: "九份老街",
    category: "spot",
    description: "山城老街、芋圓與《神隱少女》氛圍",
    popularity: 93,
    latitude: 25.1098,
    longitude: 121.8439,
    tags: ["一日遊", "老街"],
    area: "九份",
  },
  {
    name: "象山步道（六巨石夜景）",
    category: "spot",
    description: "免費拍 101 夜景的經典健行路線",
    popularity: 91,
    latitude: 25.0275,
    longitude: 121.5719,
    tags: ["夜景", "健行"],
    area: "信義",
  },
  {
    name: "士林夜市",
    category: "food",
    description: "豪大大雞排、蚵仔煎、胡椒餅",
    popularity: 90,
    latitude: 25.088,
    longitude: 121.524,
    tags: ["夜市", "必吃"],
    area: "士林",
  },
  {
    name: "國立故宮博物院",
    category: "spot",
    description: "翠玉白菜、肉形石，東亞重要博物館",
    popularity: 89,
    latitude: 25.1024,
    longitude: 121.5485,
    tags: ["博物館", "文化"],
    area: "士林",
  },
  {
    name: "寧夏夜市",
    category: "food",
    description: "觀光客較少、滷味與豬肝湯在地推薦",
    popularity: 87,
    latitude: 25.0565,
    longitude: 121.5155,
    tags: ["夜市", "在地"],
    area: "大同",
  },
  {
    name: "西門町徒步區",
    category: "spot",
    description: "潮流購物、街頭表演、電影街",
    popularity: 86,
    latitude: 25.042,
    longitude: 121.508,
    tags: ["購物", "年輕"],
    area: "萬華",
  },
  {
    name: "鼎泰豐（信義本店）",
    category: "food",
    description: "小籠包代名詞，米其林一星",
    popularity: 85,
    latitude: 25.0335,
    longitude: 121.564,
    tags: ["必吃", "排隊"],
    area: "信義",
  },
  {
    name: "迪化街 & 大稻埕",
    category: "spot",
    description: "年貨大街、霞海城隍廟、老宅咖啡",
    popularity: 84,
    latitude: 25.058,
    longitude: 121.5098,
    tags: ["文化", "老街"],
    area: "大同",
  },
  {
    name: "松山文創園區",
    category: "spot",
    description: "舊菸廠改建，展覽、設計選物",
    popularity: 82,
    latitude: 25.0436,
    longitude: 121.5606,
    tags: ["文創", "展覽"],
    area: "信義",
  },
  {
    name: "阿宗麵線（西門町）",
    category: "food",
    description: "站著吃的麵線，觀光客排隊名攤",
    popularity: 81,
    latitude: 25.0422,
    longitude: 121.5065,
    tags: ["小吃", "排隊"],
    area: "萬華",
  },
  {
    name: "貓空纜車 & 茶園",
    category: "spot",
    description: "茶飲、夜景、鐵壺茶體驗",
    popularity: 80,
    latitude: 24.968,
    longitude: 121.586,
    tags: ["夜景", "郊遊"],
    area: "文山",
  },
  {
    name: "華西街夜市 & 剝皮寮",
    category: "food",
    description: "台灣小吃縮影，鄰近龍山寺",
    popularity: 78,
    latitude: 25.037,
    longitude: 121.4995,
    tags: ["夜市", "文化"],
    area: "萬華",
  },
  {
    name: "北投溫泉博物館 & 溫泉街",
    category: "spot",
    description: "日式溫泉旅館、硫磺湯",
    popularity: 77,
    latitude: 25.1365,
    longitude: 121.5065,
    tags: ["溫泉", "放鬆"],
    area: "北投",
  },
  {
    name: "阜杭豆漿",
    category: "food",
    description: "厚燒餅、鹹豆漿，早餐排隊傳奇",
    popularity: 76,
    latitude: 25.0442,
    longitude: 121.5325,
    tags: ["早餐", "排隊"],
    area: "中正",
  },
  {
    name: "饒河街觀光夜市",
    category: "food",
    description: "胡椒餅、藥燉排骨、慈祐宮",
    popularity: 75,
    latitude: 25.0505,
    longitude: 121.5775,
    tags: ["夜市"],
    area: "松山",
  },
  {
    name: "陽明山竹子湖（季節限定）",
    category: "spot",
    description: "海芋、繡球花季，郊遊健行",
    popularity: 70,
    latitude: 25.182,
    longitude: 121.534,
    tags: ["花季", "郊遊"],
    area: "北投",
  },
];
