import type { DiscoverCard } from "@/types/discover";

export const TOKYO_CARDS: Omit<DiscoverCard, "id">[] = [
  {
    name: "淺草寺 & 仲見世通",
    category: "spot",
    description: "雷門、人形燒、傳統東京風情",
    popularity: 97,
    latitude: 35.7148,
    longitude: 139.7967,
    tags: ["必訪", "寺廟"],
    area: "淺草",
  },
  {
    name: "澀谷 Scramble Crossing",
    category: "spot",
    description: "世界 busiest 十字路口、忠犬八公",
    popularity: 96,
    latitude: 35.6595,
    longitude: 139.7004,
    tags: ["地標", "必訪"],
    area: "澀谷",
  },
  {
    name: "東京晴空塔",
    category: "spot",
    description: "634m 展望台、墨田水族館",
    popularity: 94,
    latitude: 35.7101,
    longitude: 139.8107,
    tags: ["地標", "夜景"],
    area: "押上",
  },
  {
    name: "築地外市場 & 壽司早餐",
    category: "food",
    description: "搬遷後仍熱鬧的海鮮丼、玉子燒",
    popularity: 93,
    latitude: 35.6654,
    longitude: 139.7707,
    tags: ["必吃", "海鮮"],
    area: "築地",
  },
  {
    name: "明治神宮",
    category: "spot",
    description: "都市森林神社、原宿入口",
    popularity: 92,
    latitude: 35.6764,
    longitude: 139.6993,
    tags: ["神社", "散步"],
    area: "原宿",
  },
  {
    name: "新宿歌舞伎町 & 黃金街",
    category: "spot",
    description: "霓虹夜生活、居酒屋小巷",
    popularity: 91,
    latitude: 35.6938,
    longitude: 139.7034,
    tags: ["夜生活"],
    area: "新宿",
  },
  {
    name: "一蘭拉麵／豚骨拉麵",
    category: "food",
    description: "個室拉麵體驗，新宿澀谷分店多",
    popularity: 90,
    latitude: 35.6896,
    longitude: 139.7006,
    tags: ["拉麵", "必吃"],
    area: "新宿",
  },
  {
    name: "秋葉原電器街",
    category: "spot",
    description: "動漫、遊戲、女僕咖啡",
    popularity: 89,
    latitude: 35.6984,
    longitude: 139.7731,
    tags: ["動漫", "購物"],
    area: "秋葉原",
  },
  {
    name: "原宿竹下通 & 表參道",
    category: "spot",
    description: "甜點、潮流、精品並列",
    popularity: 88,
    latitude: 35.6717,
    longitude: 139.7036,
    tags: ["年輕", "購物"],
    area: "原宿",
  },
  {
    name: "銀座（和牛、壽司、百貨）",
    category: "food",
    description: "高級 dining、週末步行者天堂",
    popularity: 87,
    latitude: 35.6717,
    longitude: 139.7649,
    tags: ["高級", "購物"],
    area: "銀座",
  },
  {
    name: "上野公園 & 博物館",
    category: "spot",
    description: "櫻花、動物園、國立博物館",
    popularity: 86,
    latitude: 35.7142,
    longitude: 139.7745,
    tags: ["博物館", "櫻花"],
    area: "上野",
  },
  {
    name: "六本木之丘 & 森美術館",
    category: "spot",
    description: "東京鐵塔夜景、當代藝術",
    popularity: 85,
    latitude: 35.6605,
    longitude: 139.7292,
    tags: ["夜景", "藝術"],
    area: "六本木",
  },
  {
    name: "台場（彩虹大橋、teamLab）",
    category: "spot",
    description: "海濱購物、未來感展覽",
    popularity: 84,
    latitude: 35.6262,
    longitude: 139.7753,
    tags: ["海景", "親子"],
    area: "台場",
  },
  {
    name: "澀谷 Sky 展望台",
    category: "spot",
    description: "360° 露天觀景，澀谷上空",
    popularity: 83,
    latitude: 35.6586,
    longitude: 139.7016,
    tags: ["夜景", "網美"],
    area: "澀谷",
  },
  {
    name: "吉祥寺 & 井之頭公園",
    category: "spot",
    description: "文青小店、週末市集、天鵝船",
    popularity: 82,
    latitude: 35.7033,
    longitude: 139.5799,
    tags: ["文青", "散步"],
    area: "吉祥寺",
  },
  {
    name: "東京迪士尼樂園",
    category: "spot",
    description: "千葉舞濱，一日遊經典",
    popularity: 81,
    latitude: 35.6329,
    longitude: 139.8804,
    tags: ["主題樂園", "一日遊"],
    area: "舞濱",
  },
  {
    name: "天婦羅／炸豬排（銀座、日本橋）",
    category: "food",
    description: "みかわ是ゝ、まい泉等名店",
    popularity: 80,
    latitude: 35.6762,
    longitude: 139.765,
    tags: ["炸物", "排隊"],
    area: "銀座",
  },
  {
    name: "池袋（動漫、水族館）",
    category: "spot",
    description: "陽光60、寶可夢中心",
    popularity: 78,
    latitude: 35.7295,
    longitude: 139.7109,
    tags: ["動漫", "購物"],
    area: "池袋",
  },
  {
    name: "增上寺 & 東京鐵塔",
    category: "spot",
    description: "紅白鐵塔與古寺同框",
    popularity: 79,
    latitude: 35.6586,
    longitude: 139.7454,
    tags: ["地標", "夜景"],
    area: "芝公園",
  },
  {
    name: "阿夫利 抹茶拉面（表参道）",
    category: "food",
    description: "小眾話題，抹茶控朝聖",
    popularity: 68,
    latitude: 35.6655,
    longitude: 139.712,
    tags: ["小眾", "拉麵"],
    area: "表參道",
  },
];
